set nocompatible
filetype off

set t_Co=256
syntax on

" vim-plug plugin manager
call plug#begin('~/.vim/plugged')

" Theme color
Plug 'morhetz/gruvbox'
set background=dark
colorscheme gruvbox

Plug 'mhinz/vim-startify'
Plug 'ervandew/supertab'
Plug 'raimondi/delimitmate'
Plug 'bronson/vim-trailing-whitespace'
Plug 'myusuf3/numbers.vim'
Plug 'tpope/vim-repeat'

" All-in-one language syntax pack
Plug 'sheerun/vim-polyglot'

Plug 'airblade/vim-gitgutter'
let g:gitgutter_grep_command = 'grep -e'

Plug 'yggdroot/indentline'
let g:indentLine_color_term = 238

" quick navigation to visible letter
Plug 'easymotion/vim-easymotion'
map  f <Plug>(easymotion-bd-f)
map  F <Plug>(easymotion-bd-f)

" useful commenting plugin
Plug 'scrooloose/nerdcommenter'
let g:NERDSpaceDelims = 1
let g:NERDTrimTrailingWhitespace = 1

" status bar at bottom
Plug 'vim-airline/vim-airline'
let g:airline_powerline_fonts = 1
set laststatus=2

" fuzzy search with fzf
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
map <c-p> :Files<CR>
map ,b :Buffers<CR>
map ,r :Rg<CR>

" surrounding text
Plug 'tpope/vim-surround'

" navigation tree
Plug 'scrooloose/nerdtree'
map ,p :NERDTreeToggle<CR>
nmap ,n :NERDTreeFind<CR>
let NERDTreeIgnore=['node_modules']

" nerdtree git plugin
Plug 'Xuyuanp/nerdtree-git-plugin'

" async linting
Plug 'dense-analysis/ale'
let g:ale_linters = {
\   'javascript': ['eslint'],
\   'typescript': ['eslint'],
\}
let g:ale_sign_error = '▶'
let g:ale_sign_warning = '▶'
let g:ale_fix_on_save = 0

call plug#end()

" quicker window movement
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

" tab to last buffer to make it easy to go to the last file you were in
nmap <Tab> :b#<CR>

" Turn on file type detection.
filetype plugin indent on

syntax enable

" Display the mode you're in.
set showmode

" handle multiple buffer better
set hidden

" enhanced command line completion
set wildmenu

" Complete files like a shell.
set wildmode=list:longest

" case-sensitive if expression contains a capital letter
set smartcase

" Intuitive backspacing
set backspace=indent,eol,start

" show line numbers.
set number

" show cursor position.
set ruler

" Turn of .swp files
set noswapfile

" Turn text wrap off
set wrap!

" Highlight matches.
set hlsearch

" Highlight matches as you type
set incsearch

" Set the terminal's title
set title

" Don't make a backup before overwriting a file
set nobackup
set nowritebackup

" Enable system clipboard
if $TMUX == ''
	set clipboard+=unnamed
endif

" Global tab width.
set tabstop=2
set shiftwidth=2
set expandtab

set autoindent

" setting the curor line highlighted
augroup CursorLine
  au!
    au VimEnter,WinEnter,BufWinEnter * setlocal cursorline
      au WinLeave * setlocal nocursorline
    augroup END
    hi CursorLine ctermbg=240
    hi Normal ctermbg=none

" Abbreviations
ab cl, console.log('==========>', );<ESC>hhi
ab des, describe('', () => {<CR>});<ESC>O
ab it, it('', () => {<CR>});<ESC>O

" Exclude from wildmenu
set wildignore+=*/tmp/*,*.so,*.swp,*.zip
