# set Zsh as default tmux shell
set-option -g default-shell /bin/zsh

set -g default-terminal "tmux-256color"
set -sa terminal-overrides ",xterm-256color:RGB"

# Tmux control key to Ctrl-a instead of Ctrl-b, easier to reach
unbind C-b
set-option -g prefix C-a
bind C-a send-prefix

# short command delay
set -sg escape-time 1

# set numbering of windows to go from 1
set -g base-index 1
setw -g pane-base-index 1

# reload Tmux configuration while using Tmux
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# vertical and horizontal symbols to split the screen
bind | split-window -h -c '#{pane_current_path}'
bind - split-window -v -c '#{pane_current_path}'

# navigate between panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize window panes with vim cmds
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# increase buffer size
set-option -g history-limit 50000

# mouse support
set -g mouse on

# renumber windows when one is closed
set -g renumber-windows on

# vi mode for copy mode
setw -g mode-keys vi

# let editors know when focus changes between panes
set -g focus-events on
